### PR TITLE
Add Japanese translation and various items

### PR DESCRIPTION
**Pull request by NaokiSato102**
・EN
I have created a Japanese translation file of Maid Fiddler.(jp.json)

The production environment is COM3D2 ver1.43.1 and Maid Fiddler ver1.0.6.0
And I checked the operation in the same environment.

In addition, to support the latest version of Maid Fiddler, some missing items have been added.
In addition, items for official mods that were automatically obtained by the Maid Fiddler function have also been added.

Please merge these items after checking the operation.

Some items have been left out of the translation due to not being able to check the game display and support, 
but we think it's a lot easier for Japanese users to use than the English version.

・JP(original)
Maid Fiddlerの日本語翻訳ファイルを作成いたしました。(jp.json)
作製環境は自分のCOM3D2 ver1.43.1とMaid Fiddler ver1.0.6.0で、同環境にて動作確認を取りました。
そして、Maid Fiddlerの最新バージョンに対応するため、不足していた項目を追加しました。
そのほか、Maid Fiddlerの機能により自動取得された公式MOD分の項目も追加されています。
動作確認の上マージをお願いいたします。

一部項目はゲーム表示と対応確認ができなかったため翻訳抜けしていますが、
日本語ユーザにとっては英語のままよりずいぶんと使いやすくなっていると思います。

### CODE REVIEW

**Comment by denikson** [comment]
Greetings!

Thanks for this contribution! From a quick test it looks like it's fine. I'll check the file and write any comments I have about it.

It would be nice if eventually you (or someone else) could finish up the translations. Nevertheless, it's still really nice that most of the things are translated!

Thank you very much 😄

**Comment by denikson** [comment]
Looks good to me.

One small note: because propensities, yotogi skills and work skills already have Japanese keys, you don't need to have those translations defined. Maid Fiddler will automatically realize to just use the Japanese name that the game provides.

No need to make any fixes, I'll merge this and remove those unneeded lines.

**Comment by NaokiSato102** [comment]
> One small note: because propensities, yotogi skills and work skills already have Japanese keys

it is all skills?
I thought it would be useful for translating other languages, so I've added the attached key. 
That's what I meant by that, too, wasn't it necessary?

At any rate, I'm glad I was able to help you.

**Comment by denikson** [comment]
You can take a look at the change I did: https://github.com/denikson/COM3D2.MaidFiddler/commit/a181e9765e410fd9f9acc9880da6f51cda1b08f6

Because those are already provided to Maid Fiddler to Japanese, you can simply remove them and Maid Fiddler will use the provided untranslated values.

You are correct that you need those for translating to other languages, but for Japanese you can leave it out because it's already "translated" by the game.

**Pull request merged**
